apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-demo
  labels:
    app: session-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-demo
  template:
    metadata:
      labels:
        app: session-demo
    spec:
      containers:
        - name: session-demo
          image: session-demo:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 80
